# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

name: 🐞 Bug
description: Create a report to help us improve
labels: ["tech-issues"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Before you open the bug report please review the following troubleshooting
        guide written by the folks at Terraform (HashCorp), which details the troubleshooting workflow for Terraform:
          - [Troubleshoot Terraform](https://developer.hashicorp.com/terraform/tutorials/configuration-language/troubleshooting-workflow)

        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Name and Version
      description: Name and version of the affected (sub-)module
      placeholder: vpc - v1.2.3
    validations:
      required: true
  - type: input
    attributes:
      label: What Terraform version are you using?
      description: Provide the version of your Terraform executable (output of `terraform version`)
      placeholder: v1.9.6
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
