name: "Run Super-Linter"

on: ["push", "pull_request"]

permissions: read-all

jobs:
  lint:
    name: Super-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Superlinter
        uses: super-linter/super-linter@v7.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (CHANGELOG.md)
          # mostly false positives
          VALIDATE_NATURAL_LANGUAGE: false
          # no support for preconditions in lifecycles
          # ref: https://github.com/tenable/terrascan/issues/1642
          VALIDATE_TERRAFORM_TERRASCAN: false
